# Generated by Django 5.2.17 on 2026-09-29 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matriculas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_validacao",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="código de validação",
                    ),
                ),
                (
                    "emitido_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="emitido em"),
                ),
                (
                    "matricula",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificado",
                        to="matriculas.matricula",
                        verbose_name="matrícula",
                    ),
                ),
            ],
            options={
                "verbose_name": "certificado",
                "verbose_name_plural": "certificados",
                "ordering": ["-emitido_em"],
            },
        ),
    ]
