# Generated by Django 5.2.17 on 2026-09-29 15:29

import apps.financeiro.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matriculas", "0002_matricula_desconto_matricula_n_parcelas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comprovante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=apps.financeiro.models._caminho_comprovante,
                        verbose_name="arquivo",
                    ),
                ),
                ("tipo_conteudo", models.CharField(max_length=40, verbose_name="tipo")),
                (
                    "enviado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="enviado em"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_analise", "Em análise"),
                            ("aprovado", "Aprovado"),
                            ("recusado", "Recusado"),
                        ],
                        default="em_analise",
                        max_length=12,
                        verbose_name="situação",
                    ),
                ),
                (
                    "motivo_recusa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="motivo da recusa"
                    ),
                ),
                (
                    "analisado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="analisado em"
                    ),
                ),
                (
                    "analisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "comprovante",
                "verbose_name_plural": "comprovantes",
                "ordering": ["-enviado_em"],
            },
        ),
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField(verbose_name="número")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor (R$)"
                    ),
                ),
                ("vencimento", models.DateField(verbose_name="vencimento")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("em_analise", "Comprovante em análise"),
                            ("paga", "Paga"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="aberta",
                        max_length=12,
                        verbose_name="situação",
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcelas",
                        to="matriculas.matricula",
                        verbose_name="matrícula",
                    ),
                ),
            ],
            options={
                "verbose_name": "parcela",
                "verbose_name_plural": "parcelas",
                "ordering": ["vencimento", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor (R$)"
                    ),
                ),
                ("data", models.DateField(verbose_name="data do pagamento")),
                (
                    "forma",
                    models.CharField(
                        choices=[("pix", "Pix"), ("dinheiro", "Dinheiro")],
                        max_length=10,
                        verbose_name="forma",
                    ),
                ),
                (
                    "codigo_transacao",
                    models.CharField(
                        blank=True,
                        help_text="O ID que aparece no comprovante do banco (opcional).",
                        max_length=64,
                        verbose_name="código da transação Pix",
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="observação"
                    ),
                ),
                (
                    "registrado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="registrado em"
                    ),
                ),
                (
                    "estornado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="estornado em"
                    ),
                ),
                (
                    "motivo_estorno",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="motivo do estorno"
                    ),
                ),
                (
                    "comprovante",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagamento",
                        to="financeiro.comprovante",
                    ),
                ),
                (
                    "recebido_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recebido por",
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagamentos",
                        to="financeiro.parcela",
                        verbose_name="parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "pagamento",
                "verbose_name_plural": "pagamentos",
                "ordering": ["-data", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="comprovante",
            name="parcela",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comprovantes",
                to="financeiro.parcela",
                verbose_name="parcela",
            ),
        ),
        migrations.AddConstraint(
            model_name="parcela",
            constraint=models.UniqueConstraint(
                fields=("matricula", "numero"), name="parcela_unica_por_numero"
            ),
        ),
        migrations.AddConstraint(
            model_name="parcela",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor__gt", 0)), name="parcela_valor_positivo"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagamento",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("codigo_transacao", ""), _negated=True),
                    ("estornado_em__isnull", True),
                ),
                fields=("codigo_transacao",),
                name="pagamento_codigo_pix_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagamento",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor__gt", 0)), name="pagamento_valor_positivo"
            ),
        ),
    ]
