# Generated by Django 5.2.17 on 2026-09-29 09:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=120, unique=True, verbose_name="nome"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "carga_horaria",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="carga horária (h)",
                    ),
                ),
                (
                    "pre_requisitos",
                    models.TextField(blank=True, verbose_name="pré-requisitos"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="0 = gratuito",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="valor (R$)",
                    ),
                ),
                (
                    "frequencia_minima",
                    models.PositiveSmallIntegerField(
                        default=75,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="frequência mínima (%)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
            ],
            options={
                "verbose_name": "curso",
                "verbose_name_plural": "cursos",
                "ordering": ["nome"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("carga_horaria__gt", 0)),
                        name="curso_carga_horaria_positiva",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valor__gte", 0)),
                        name="curso_valor_nao_negativo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("frequencia_minima__lte", 100)),
                        name="curso_frequencia_minima_ate_100",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Instrutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone"
                    ),
                ),
                (
                    "especialidades",
                    models.TextField(blank=True, verbose_name="especialidades"),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrutor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "instrutor",
                "verbose_name_plural": "instrutores",
                "ordering": ["nome"],
            },
        ),
    ]
