# Generated by Django 5.2.17 on 2026-09-29 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="parcelas_max",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="1 = só à vista",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="máximo de parcelas",
            ),
        ),
    ]
