# Generated by Django 5.2.17 on 2026-09-30 19:00

import math

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def para_mensalidade(apps, schema_editor):
    """Estima duração e horas por aula pelas turmas e divide o valor total em mensalidades."""
    Curso = apps.get_model("catalogo", "Curso")
    Turma = apps.get_model("turmas", "Turma")
    for curso in Curso.objects.all():
        turmas = list(Turma.objects.filter(curso_id=curso.pk).order_by("data_inicio"))
        meses = max(
            [math.ceil(((t.data_fim - t.data_inicio).days + 1) / 30.44) for t in turmas] or [1]
        )
        curso.duracao_meses = min(max(meses, 1), 36)
        if turmas:
            t = turmas[0]
            minutos = (t.hora_fim.hour * 60 + t.hora_fim.minute) - (t.hora_inicio.hour * 60 + t.hora_inicio.minute)
            meias_horas = round(minutos / 30)
            curso.horas_por_aula = min(max(Decimal(meias_horas) / 2, Decimal("0.5")), Decimal("12"))
        curso.valor_mensalidade = (curso.valor / curso.duracao_meses).quantize(Decimal("0.01"))
        curso.save(update_fields=["duracao_meses", "horas_por_aula", "valor_mensalidade"])


def para_valor_total(apps, schema_editor):
    Curso = apps.get_model("catalogo", "Curso")
    for curso in Curso.objects.all():
        curso.valor = curso.valor_mensalidade * curso.duracao_meses
        curso.parcelas_max = min(curso.duracao_meses, 12)
        curso.save(update_fields=["valor", "parcelas_max"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_curso_parcelas_max"),
        ("turmas", "0002_feriado"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="duracao_meses",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Tempo total do curso. Também é o número de mensalidades.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(36),
                ],
                verbose_name="duração (meses)",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="horas_por_aula",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2"),
                help_text="Ex.: 2 ou 1,5",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.5")),
                    django.core.validators.MaxValueValidator(Decimal("12")),
                ],
                verbose_name="duração da aula (h)",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="valor_mensalidade",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="0 = gratuito",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="mensalidade (R$)",
            ),
        ),
        migrations.RunPython(para_mensalidade, para_valor_total),
        migrations.RemoveConstraint(
            model_name="curso",
            name="curso_valor_nao_negativo",
        ),
        migrations.RemoveField(
            model_name="curso",
            name="parcelas_max",
        ),
        migrations.RemoveField(
            model_name="curso",
            name="valor",
        ),
        migrations.AddConstraint(
            model_name="curso",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor_mensalidade__gte", 0)),
                name="curso_mensalidade_nao_negativa",
            ),
        ),
        migrations.AddConstraint(
            model_name="curso",
            constraint=models.CheckConstraint(
                condition=models.Q(("duracao_meses__gt", 0)),
                name="curso_duracao_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="curso",
            constraint=models.CheckConstraint(
                condition=models.Q(("horas_por_aula__gt", 0)),
                name="curso_aula_positiva",
            ),
        ),
    ]
