# Generated by Django 5.2.17 on 2026-09-30 20:40

import math
from decimal import Decimal

import apps.catalogo.models
import django.core.validators
from django.db import migrations, models


def para_calculo(apps, schema_editor):
    """Dias por semana = o mínimo que cumpria a carga antiga; carga recalculada; pré-requisitos pelo nome."""
    Curso = apps.get_model("catalogo", "Curso")
    cursos = list(Curso.objects.all())
    for curso in cursos:
        semanas = curso.duracao_meses * 4
        aulas = math.ceil(Decimal(curso.carga_horaria) / curso.horas_por_aula)
        curso.dias_por_semana = min(max(math.ceil(aulas / semanas), 1), 6)
        curso.carga_horaria = math.ceil(semanas * curso.dias_por_semana * curso.horas_por_aula)
        curso.save(update_fields=["dias_por_semana", "carga_horaria"])
        texto = (curso.pre_requisitos_texto or "").lower()
        curso.pre_requisitos.set([c for c in cursos if c.pk != curso.pk and c.nome.lower() in texto])


def para_texto(apps, schema_editor):
    Curso = apps.get_model("catalogo", "Curso")
    for curso in Curso.objects.all():
        curso.pre_requisitos_texto = ", ".join(curso.pre_requisitos.values_list("nome", flat=True))
        curso.save(update_fields=["pre_requisitos_texto"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_mensalidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="aceita_outra_escola",
            field=models.BooleanField(
                default=True,
                help_text="Na matrícula, permite informar que o aluno fez o pré-requisito em outra escola.",
                verbose_name="aceita pré-requisito feito em outra escola",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="dias_por_semana",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="De 1 a 6 (segunda a sábado).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="mínimo de dias de aula por semana",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="carga_horaria",
            field=models.PositiveIntegerField(
                editable=False,
                help_text="Calculada: meses × 4 semanas × dias por semana × horas por aula.",
                verbose_name="carga horária (h)",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="horas_por_aula",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2"),
                help_text="Ex.: 2 ou 1,5",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.5")),
                    django.core.validators.MaxValueValidator(Decimal("12")),
                    apps.catalogo.models.validar_quarto_de_hora,
                ],
                verbose_name="mínimo de horas por aula",
            ),
        ),
        migrations.RenameField(
            model_name="curso",
            old_name="pre_requisitos",
            new_name="pre_requisitos_texto",
        ),
        migrations.AddField(
            model_name="curso",
            name="pre_requisitos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cursos que o aluno precisa ter concluído antes.",
                related_name="libera",
                to="catalogo.curso",
                verbose_name="pré-requisitos",
            ),
        ),
        migrations.RunPython(para_calculo, para_texto),
        migrations.RemoveField(
            model_name="curso",
            name="pre_requisitos_texto",
        ),
        migrations.RemoveField(
            model_name="curso",
            name="descricao",
        ),
        migrations.AddConstraint(
            model_name="curso",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("dias_por_semana__gte", 1), ("dias_por_semana__lte", 6)
                ),
                name="curso_dias_por_semana_1_a_6",
            ),
        ),
    ]
