# Generated by Django 5.2.17 on 2026-09-29 09:39

import apps.turmas.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Ex.: INF-2026-01",
                        max_length=30,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="data de início")),
                ("data_fim", models.DateField(verbose_name="data de término")),
                (
                    "dias_semana",
                    models.CharField(
                        help_text="Separados por vírgula. Ex.: seg,qua",
                        max_length=40,
                        validators=[apps.turmas.models.validar_dias_semana],
                        verbose_name="dias da semana",
                    ),
                ),
                ("hora_inicio", models.TimeField(verbose_name="hora de início")),
                ("hora_fim", models.TimeField(verbose_name="hora de término")),
                (
                    "sala",
                    models.CharField(blank=True, max_length=50, verbose_name="sala"),
                ),
                (
                    "vagas",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="vagas",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejada", "Planejada"),
                            ("inscricoes_abertas", "Inscrições abertas"),
                            ("em_andamento", "Em andamento"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="planejada",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turmas",
                        to="catalogo.curso",
                        verbose_name="curso",
                    ),
                ),
                (
                    "instrutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turmas",
                        to="catalogo.instrutor",
                        verbose_name="instrutor",
                    ),
                ),
            ],
            options={
                "verbose_name": "turma",
                "verbose_name_plural": "turmas",
                "ordering": ["-data_inicio", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="data")),
                ("conteudo", models.TextField(blank=True, verbose_name="conteúdo")),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="turmas.turma",
                        verbose_name="turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "aula",
                "verbose_name_plural": "aulas",
                "ordering": ["data"],
            },
        ),
        migrations.AddConstraint(
            model_name="turma",
            constraint=models.CheckConstraint(
                condition=models.Q(("vagas__gt", 0)), name="turma_vagas_positivas"
            ),
        ),
        migrations.AddConstraint(
            model_name="turma",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_fim__gte", models.F("data_inicio"))),
                name="turma_periodo_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="turma",
            constraint=models.CheckConstraint(
                condition=models.Q(("hora_fim__gt", models.F("hora_inicio"))),
                name="turma_horario_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="aula",
            constraint=models.UniqueConstraint(
                fields=("turma", "data"), name="aula_unica_por_turma_data"
            ),
        ),
    ]
