# Generated by Django 5.2.17 on 2026-09-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feriado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(unique=True, verbose_name="data")),
                (
                    "descricao",
                    models.CharField(max_length=120, verbose_name="descrição"),
                ),
            ],
            options={
                "verbose_name": "feriado",
                "verbose_name_plural": "feriados",
                "ordering": ["data"],
            },
        ),
    ]
