# Generated by Django 5.2.17 on 2026-09-29 09:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alunos", "0001_initial"),
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="data"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativa", "Ativa"),
                            ("lista_espera", "Lista de espera"),
                            ("concluida", "Concluída"),
                            ("desistente", "Desistente"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="ativa",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matriculas",
                        to="alunos.aluno",
                        verbose_name="aluno",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matriculas",
                        to="turmas.turma",
                        verbose_name="turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "matrícula",
                "verbose_name_plural": "matrículas",
                "ordering": ["data", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Frequencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "presente",
                    models.BooleanField(default=False, verbose_name="presente"),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="observação"
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="turmas.aula",
                        verbose_name="aula",
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="matriculas.matricula",
                        verbose_name="matrícula",
                    ),
                ),
            ],
            options={
                "verbose_name": "frequência",
                "verbose_name_plural": "frequências",
                "ordering": ["aula__data"],
            },
        ),
        migrations.AddConstraint(
            model_name="matricula",
            constraint=models.UniqueConstraint(
                fields=("aluno", "turma"), name="matricula_unica_aluno_turma"
            ),
        ),
        migrations.AddConstraint(
            model_name="frequencia",
            constraint=models.UniqueConstraint(
                fields=("matricula", "aula"), name="frequencia_unica_matricula_aula"
            ),
        ),
    ]
