# Generated by Django 5.2.17 on 2026-09-29 15:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matriculas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matricula",
            name="desconto",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="100 = bolsa integral",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="desconto (%)",
            ),
        ),
        migrations.AddField(
            model_name="matricula",
            name="n_parcelas",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="número de parcelas",
            ),
        ),
    ]
