# Generated by Django 5.2.17 on 2026-09-30 19:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matriculas", "0002_matricula_desconto_matricula_n_parcelas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matricula",
            name="n_parcelas",
        ),
        migrations.AlterField(
            model_name="matricula",
            name="desconto",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Vale para todas as mensalidades. 100 = bolsa integral",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="desconto (%)",
            ),
        ),
    ]
