# Generated by Django 5.2.17 on 2026-09-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matriculas", "0003_mensalidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="matricula",
            name="pre_requisito_outra_escola",
            field=models.BooleanField(
                default=False,
                help_text="Marcado quando o aluno entrou sem ter concluído o pré-requisito nesta escola.",
                verbose_name="pré-requisito feito em outra escola",
            ),
        ),
    ]
