# Generated by Django 5.2.17 on 2026-09-29 09:39

import apps.alunos.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                (
                    "cpf",
                    models.CharField(
                        help_text="Somente números",
                        max_length=11,
                        unique=True,
                        validators=[apps.alunos.validators.validar_cpf],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="data de nascimento"),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="endereço"
                    ),
                ),
                (
                    "escolaridade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fund_inc", "Fundamental incompleto"),
                            ("fund_comp", "Fundamental completo"),
                            ("medio_inc", "Médio incompleto"),
                            ("medio_comp", "Médio completo"),
                            ("sup_inc", "Superior incompleto"),
                            ("sup_comp", "Superior completo"),
                        ],
                        max_length=12,
                        verbose_name="escolaridade",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aluno",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "aluno",
                "verbose_name_plural": "alunos",
                "ordering": ["nome"],
            },
        ),
    ]
